-- Create the table
create table hotels (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  location text not null,
  price float8 not null,
  rating float8 not null,
  amenities text[] null,
  description text null
);

-- Enable Row Level Security (RLS) - Optional for Workshop
alter table hotels enable row level security;

-- Create a policy that allows anyone to read
create policy "Public hotels are viewable by everyone."
  on hotels for select
  using ( true );

-- Create a policy that allows anyone to insert (For seeding script to work easily with Anon key)
-- WARNING: In a real app, strict this to Service Role only.
create policy "Anyone can insert hotels"
  on hotels for insert
  with check ( true );
